// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuE73UucrfvZI6zyEtc_WLDdV_8wduzD8',
    appId: '1:483835472818:web:92bfeae8a10063f114d2ab',
    messagingSenderId: '483835472818',
    projectId: 'new-paks',
    authDomain: 'new-paks.firebaseapp.com',
    storageBucket: 'new-paks.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNvr6tbU3poxDdf5K3Dk4-2GONFLThPs0',
    appId: '1:483835472818:android:384f80fb5f67518414d2ab',
    messagingSenderId: '483835472818',
    projectId: 'new-paks',
    storageBucket: 'new-paks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvja-g8s9bMbL78POYC6DsNYE10QDiWEA',
    appId: '1:483835472818:ios:40722ba5023ac2a514d2ab',
    messagingSenderId: '483835472818',
    projectId: 'new-paks',
    storageBucket: 'new-paks.appspot.com',
    iosClientId: '483835472818-i0jfbfi3l7hi579pleb13niv59n7t3jq.apps.googleusercontent.com',
    iosBundleId: 'com.example.paks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvja-g8s9bMbL78POYC6DsNYE10QDiWEA',
    appId: '1:483835472818:ios:40722ba5023ac2a514d2ab',
    messagingSenderId: '483835472818',
    projectId: 'new-paks',
    storageBucket: 'new-paks.appspot.com',
    iosClientId: '483835472818-i0jfbfi3l7hi579pleb13niv59n7t3jq.apps.googleusercontent.com',
    iosBundleId: 'com.example.paks',
  );
}
